# Site settings
title: Christophe Lieutaud - Cabinet d’Ostéopathie
description: "Installé depuis 2014, Christophe Lieutaud est Ostépathe diplômé de l’école IFOGA d’Avignon après 5 années d’études et un mémoire sur les dysfonctions musculaires liées à la pratique sportive."
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the name of your domain
logo_url: svg/min/logo.svg

# Hero
hero: 
    hero_img: hero.jpg
    hero_title: Christophe Lieutaud
    hero_description: Cabinet d’Ostéopathie à Vaison la Romaine

# Contact form
api_token: # Enter API token here

# Contact info
contact:
    phone: +33 6 14 53 60 38
    emergency: 15
    email:  contact@lieutaud-osteopathe-vaison.fr
    address: Cabinet médical Le Lynx<br/>1 rue des Frères Lumières<br/>84110 Vaison la Romaine

# Opening hours
monday_friday-title: Lundi au Vendredi
monday_friday-value: de 8h à 20H
# Testimonials
testimonials:
    testimonials_img: parallax.jpg
# Social settings
facebook: http://facebook.com
twitter: http://twitter.com
instagram: http://instagram.com
youtube: http://youtube.com
skype: skype:obaez_design?userinfo
feed: yes

# Footer
copyright: © 2020 Christophe Lieutaud - Cabinet d’Ostéopathie - Tous droits réservés

# Build settings
markdown: kramdown

exclude: [
    package.json,
    Gruntfile.js,
    node_modules,
    .sass-cache,
    Gemfile,
    Gemfile.lock,
    .gitignore
]

# Theme Settings
analytics: 
google_verification:
